name: Build Debian package

on: [pull_request]

env:
  DEBEMAIL: support@mekomsolutions.com
  DEBFULLNAME: Mekom Solutions

jobs:
  build-deb:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - run: apt-get update

      - name: Install dependencies
        run: apt-get install -qq -y dh-make devscripts build-essential dh-systemd

      - name: Build usb-autorunner-dev
        working-directory: ./usb-autorunner-dev
        run: debuild -us -uc

      - name: Build usb-autorunner
        working-directory: ./usb-autorunner
        run: debuild -us -uc

      - name: Build usb-autorunner-profiles
        working-directory: ./usb-autorunner-profiles
        run: debuild -us -uc
